import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Client from "@/utils/client";
import Login from "./components/Login";
import { getSession } from "@/lib/userActions";
import Link from "next/link";
import { FaHome } from "react-icons/fa";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const ses = await getSession()

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="paddedContainer">
          <div> <Link id="homeButton" href={"/"}> <FaHome /> <p>home</p> </Link> </div>
          { ses != null ? children : <Login /> }
        </div>
      </body>
    </html>
  );
}
